### ISSUE TITLE
Source in MOC improvment

### ISSUE THREAD

**Issue by ianmbus** [H-E-L-P/XID_plus#68]
The check_in_moc function in moc_rountines.py is slower than the inMoc Function in herschelhelp_python. I found it makes a significant improvement in speed when defining the prior and prior catalogue

Ian

**Comment by pdh21** [comment]
Have made the suggested change. Having had issues with this for Herschel-Stripe82, I have noticed that if you are using a moc based on sources, the higher the order of moc, the slower it is and by the power of 2 (because you have four times the number of pixels in moc as you go to next highest order)
